server:
  port: 8080

spring:
  application:
    name: learn-api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://LEARN-AUTH-SERVICE
          predicates:
            - Path=/learn-auth/**
        - id: course-service
          uri: lb://LEARN-COURSE-SERVICE
          predicates:
            - Path=/learn-course/**
        - id: purchase-service
          uri: lb://LEARN-PURCHASE-SERVICE
          predicates:
            - Path=/learn-purchase/**


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
