name: Continuous Integration GitHub Actions

on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentiasl
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.WS_SECRET_ACCESS_KEY  }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION  }}

    - name: Login to Amazon ECR Hub
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1    

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build application JAR
      working-directory: .
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: .
      run: docker-compose build

    - name: Build, tag, and push docker image to Amazon ECR
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:latest ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:latest ${{ secrets.IMAGE_REPO_URL }}:latest

        docker push ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
        docker push ${{ secrets.IMAGE_REPO_URL }}:latest 

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/learn-authuser:latest ${{ secrets.DOCKER_USERNAME }}/learn-authuser:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/learn-authuser:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/learn-authuser:latest
