name: Continuous Integration GitHub Actions

on:
  push:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1    

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build application JAR
      working-directory: .
      run: mvn clean package

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:latest .

    - name: Tag Docker image for ECR
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:latest ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:latest ${{ secrets.IMAGE_REPO_URL }}:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
        docker push ${{ secrets.IMAGE_REPO_URL }}:latest 

    - name: Tag Docker image for Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:${{ github.run_id }}
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/learn-api-gateway:latest
